import { Inter } from "next/font/google";
import "./globals.css";
import './fonts.css'
import NavBar from "@/components/home/NavBar";
import Footer from "@/components/home/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-slate-200`}>
      <NavBar/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
